DELETE FROM `trinity_string` WHERE `entry` BETWEEN 13401 AND 13443;
INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES 
(13401, 'Alchemy', NULL, NULL, NULL, NULL, NULL, 'Alquimia', 'Alquimia', NULL),
(13402, 'Skinning', NULL, NULL, NULL, NULL, NULL, 'Desuello', 'Desuello', NULL),
(13403, 'Enchanting', NULL, NULL, NULL, NULL, NULL, 'Encantamiento', 'Encantamiento', NULL),
(13404, 'Herbalism', NULL, NULL, NULL, NULL, NULL, 'Herbolisteria', 'Herbolisteria', NULL),
(13405, 'Engineering', NULL, NULL, NULL, NULL, NULL, 'Ingeniería', 'Ingeniería', NULL),
(13406, 'Inscription', NULL, NULL, NULL, NULL, NULL, 'Inscripción', 'Inscripción', NULL),
(13407, 'Jewelcrafting', NULL, NULL, NULL, NULL, NULL, 'Joyería', 'Joyería', NULL),
(13408, 'Mining', NULL, NULL, NULL, NULL, NULL, 'Minería', 'Minería', NULL),
(13409, 'Leatherworking', NULL, NULL, NULL, NULL, NULL, 'Peletería', 'Peletería', NULL),
(13410, 'Tailoring', NULL, NULL, NULL, NULL, NULL, 'Sastrería', 'Sastrería', NULL),
(13411, 'Blacksmithing', NULL, NULL, NULL, NULL, NULL, 'Herrería', 'Herrería', NULL),
(13412, 'Give me my promotion  ', NULL, NULL, NULL, NULL, NULL, 'Dame mi promoción  ', 'Dame mi promoción  ', NULL),
(13413, 'Give me my promotion  ', NULL, NULL, NULL, NULL, NULL, 'Dame mi promoción  ', 'Dame mi promoción  ', NULL),
(13414, 'Warrior Arms  ', NULL, NULL, NULL, NULL, NULL, 'Guerrero Armas  ', 'Guerrero Armas  ', NULL),
(13415, 'Warrior Fury  ', NULL, NULL, NULL, NULL, NULL, 'Guerrero Furia  ', 'Guerrero Furia  ', NULL),
(13416, 'Warrior Protect  ', NULL, NULL, NULL, NULL, NULL, 'Guerrero Protección  ', 'Guerrero Protección  ', NULL),
(13417, 'Warrior Arms  ', NULL, NULL, NULL, NULL, NULL, 'Guerrero Armas  ', 'Guerrero Armas  ', NULL),
(13418, 'Warrior Fury  ', NULL, NULL, NULL, NULL, NULL, 'Guerrero Furia  ', 'Guerrero Furia  ', NULL),
(13419, 'Warrior Protect  ', NULL, NULL, NULL, NULL, NULL, 'Guerrero Protección  ', 'Guerrero Protección  ', NULL),
(13420, 'Paladin Retri  ', NULL, NULL, NULL, NULL, NULL, 'Paladin Retri  ', 'Paladin Retri  ', NULL),
(13421, 'Paladin Protect  ', NULL, NULL, NULL, NULL, NULL, 'Paladin Protect  ', 'Paladin Protect  ', NULL),
(13422, 'Paladin Holy  ', NULL, NULL, NULL, NULL, NULL, 'Paladin Holy  ', 'Paladin Holy  ', NULL),
(13423, 'Paladin Retri  ', NULL, NULL, NULL, NULL, NULL, 'Paladin Retri  ', 'Paladin Retri  ', NULL),
(13424, 'Paladin Protect  ', NULL, NULL, NULL, NULL, NULL, 'Paladin Protect  ', 'Paladin Protect  ', NULL),
(13425, 'Paladin Holy  ', NULL, NULL, NULL, NULL, NULL, 'Paladin Holy  ', 'Paladin Holy  ', NULL),
(13426, 'Priest Heal  ', NULL, NULL, NULL, NULL, NULL, 'Priest Heal  ', 'Priest Heal  ', NULL),
(13427, 'Priest Shadow  ', NULL, NULL, NULL, NULL, NULL, 'Priest Sombras  ', 'Priest Sombras  ', NULL),
(13428, 'Priest Heal  ', NULL, NULL, NULL, NULL, NULL, 'Priest Heal  ', 'Priest Heal  ', NULL),
(13429, 'Priest Shadow  ', NULL, NULL, NULL, NULL, NULL, 'Priest Sombras  ', 'Priest Sombras  ', NULL),
(13430, 'Shaman Heal  ', NULL, NULL, NULL, NULL, NULL, 'Chamán Heal  ', 'Chamán Heal  ', NULL),
(13431, 'Shaman Elemental  ', NULL, NULL, NULL, NULL, NULL, 'Chamán Elemental  ', 'Chamán Elemental  ', NULL),
(13432, 'Shaman Enhancement  ', NULL, NULL, NULL, NULL, NULL, 'Chamán Mejora  ', 'Chamán Mejora  ', NULL),
(13433, 'Shaman Heal  ', NULL, NULL, NULL, NULL, NULL, 'Chamán Heal  ', 'Chamán Heal  ', NULL),
(13434, 'Shaman Elemental  ', NULL, NULL, NULL, NULL, NULL, 'Chamán Elemental  ', 'Chamán Elemental  ', NULL),
(13435, 'Shaman Enhancement  ', NULL, NULL, NULL, NULL, NULL, 'Chamán Mejora  ', 'Chamán Mejora  ', NULL),
(13436, 'Druid Caster  ', NULL, NULL, NULL, NULL, NULL, 'Druida Caster  ', 'Druida Caster  ', NULL),
(13437, 'Druid Heal  ', NULL, NULL, NULL, NULL, NULL, 'Druida Heal  ', 'Druida Heal  ', NULL),
(13438, 'Druid Feral  ', NULL, NULL, NULL, NULL, NULL, 'Druida Feral  ', 'Druid Feral  ', NULL),
(13439, 'Druid Caster  ', NULL, NULL, NULL, NULL, NULL, 'Druida Caster  ', 'Druida Caster  ', NULL),
(13440, 'Druid Heal  ', NULL, NULL, NULL, NULL, NULL, 'Druida Heal  ', 'Druida Heal  ', NULL),
(13441, 'Druid Feral  ', NULL, NULL, NULL, NULL, NULL, 'Druida Feral  ', 'Druid Feral  ', NULL),
(13442, 'Teleport to Stormwind', NULL, NULL, NULL, NULL, NULL, 'Teletransporte a Ventormenta', 'Teletransporte a Ventormenta', NULL),
(13443, 'Teleport to Orgrimmar', NULL, NULL, NULL, NULL, NULL, 'Teletransporte a Orgrimmar', 'Teletransporte a Orgrimmar', NULL);