DELETE FROM `access_requirement` WHERE `mapId`=959 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (959, 'DUNGEON_NORMAL', 87, 0, 0, 0, 0, 30752, 30752, 0, NULL, 'Shado-Pan Monastery - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=959 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (959, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Shado-Pan Monastery - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=960 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (960, 'DUNGEON_NORMAL', 85, 0, 0, 0, 0, 0, 0, 0, NULL, 'Temple of the Jade Serpent - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=960 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (960, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Temple of the Jade Serpent - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=961 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (961, 'DUNGEON_NORMAL', 85, 0, 0, 0, 0, 0, 0, 0, NULL, 'Stormstout Brewery - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=961 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (961, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Stormstout Brewery - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=962 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (962, 'DUNGEON_NORMAL', 88, 0, 0, 0, 0, 0, 0, 0, NULL, 'Gate of the Setting Sun - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=962 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (962, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Gate of the Setting Sun - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=994 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (994, 'DUNGEON_NORMAL', 87, 0, 0, 0, 0, 0, 0, 0, NULL, 'Mogushan Palace - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=994 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (994, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Mogushan Palace - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1001 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1001, 'DUNGEON_NORMAL', 21, 0, 0, 0, 0, 0, 0, 0, NULL, 'Scarlet Halls - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1001 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1001, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Scarlet Halls - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1004 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1004, 'DUNGEON_NORMAL', 23, 0, 0, 0, 0, 0, 0, 0, NULL, 'Scarlet Monastery - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1004 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1004, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Scarlet Monastery - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1007 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1007, 'DUNGEON_NORMAL', 33, 0, 0, 0, 0, 0, 0, 0, NULL, 'Scholomance - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1007 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1007, 'DUNGEON_HEROIC', 99, 0, 0, 0, 0, 0, 0, 0, NULL, 'Scholomance - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1011 AND `difficulty`='DUNGEON_NORMAL';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1011, 'DUNGEON_NORMAL', 88, 0, 0, 0, 0, 0, 0, 0, NULL, 'Siege of Niuzao Temple - Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1011 AND `difficulty`='DUNGEON_HEROIC';
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item_level`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1011, 'DUNGEON_HEROIC', 90, 0, 0, 0, 0, 0, 0, 0, NULL, 'Siege of Niuzao Temple - Entrance');

DELETE FROM `disables` WHERE `sourceType` = '2' AND `entry` = '1007'; 
DELETE FROM `disables` WHERE `sourceType` = '2' AND `entry` = '1001'; 